import * as XLSX from 'xlsx';import type {AppData,PlanRow,Front,Capability,RouteNorm} from '@/types/domain';
const str=(v:unknown)=>String(v??'').trim(); const num=(v:unknown)=>Number(v);
export async function importWorkbook(file:File):Promise<AppData>{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const sheet=(name:string)=>XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[name]!,{defval:''});
const rows:PlanRow[]=sheet('Календарный график').map((r,i)=>({id:str(r['ID строки']||i+1),date:toISO(r['Дата']),region:str(r['Регион назначения']),station:str(r['Станция назначения']),recipient:str(r['Получатель'])||undefined,cargoCode:str(r['Код груза']),cargoName:str(r['Наименование груза'])||undefined,frontCode:str(r['Код фронта']),wagons:num(r['Количество вагонов'])}));
const fronts:Front[]=sheet('Фронты').map(r=>({code:str(r['Код фронта']),name:str(r['Наименование']),placementCapacity:num(r['Вместимость одной постановки']),dailyCapacity:num(r['Суточная производительность'])}));
const capabilities:Capability[]=sheet('Грузы по фронтам').map(r=>({frontCode:str(r['Код фронта']),cargoCode:str(r['Код груза'])}));
const norms:RouteNorm[]=sheet('Нормы маршрутов').filter(r=>str(r['Регион назначения'])!=='DEFAULT').map(r=>({region:str(r['Регион назначения']),norm:num(r['Норма'])}));
const def=sheet('Нормы маршрутов').find(r=>str(r['Регион назначения'])==='DEFAULT'); const period=rows[0]?.date.slice(0,7);
return {rows,fronts,capabilities,norms,settings:{backDays:2,forwardDays:2,defaultNorm:num(def?.['Норма']||72)},fileName:file.name,period};}
function toISO(v:unknown){if(v instanceof Date)return v.toISOString().slice(0,10);const s=str(v);const m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);return m?`${m[3]}-${m[2]!.padStart(2,'0')}-${m[1]!.padStart(2,'0')}`:s.slice(0,10)}
export function exportResult(data:AppData){const wb=XLSX.utils.book_new();const r=data.result;if(!r)return;XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.routes),'Маршруты');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.potentialRoutes),'Потенциальные');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.movements),'Перемещения');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.remainders),'Остатки');XLSX.writeFile(wb,`optimized-${data.period??'plan'}.xlsx`)}
